export const siteConfig = {
  name: 'InternetOne.live',
  description: 'Compare internet and TV packages from leading providers. Check availability by location and connect with specialists for plan guidance.',
  url: 'https://internetone.live',
  
  contact: {
    phone: '(888) 524-0250',
    phoneRaw: '+18885240250',
    phoneFormatted: '(888) 524-0250',
    email: 'support@Internetone.live',
    hours: 'Mon–Fri 9AM–6PM EST',
  },
  
  disclaimers: {
    independence: 'InternetOne.live is an independent comparison and connection service and is not affiliated with, endorsed by, or sponsored by Verizon, Spectrum, AT&T, or Optimum.',
    trademarks: 'Provider names and trademarks belong to their respective owners.',
    pricing: 'Availability and pricing vary by location and are subject to change.',
    affiliate: 'InternetOne.live is an independent comparison and connection service.',
    full: 'InternetOne.live is an independent comparison and connection service and is not affiliated with, endorsed by, or sponsored by Verizon, Spectrum, AT&T, or Optimum. Provider names and trademarks belong to their respective owners. Availability and pricing vary by location and are subject to change.',
  },
  
  providers: [
    {
      id: 'verizon',
      name: 'Verizon',
      slug: 'verizon',
      color: '#cd040b',
      colorLight: '#ff1a21',
      colorDark: '#a00308',
      tagline: 'Explore Verizon Internet Options',
    },
    {
      id: 'spectrum',
      name: 'Spectrum',
      slug: 'spectrum',
      color: '#0066cc',
      colorLight: '#1a7fef',
      colorDark: '#004d99',
      tagline: 'Explore Spectrum Internet Options',
    },
    {
      id: 'att',
      name: 'AT&T',
      slug: 'att',
      color: '#00a8e0',
      colorLight: '#33c4f0',
      colorDark: '#0088b8',
      tagline: 'Explore AT&T Internet Options',
    },
    {
      id: 'optimum',
      name: 'Optimum',
      slug: 'optimum',
      color: '#f26522',
      colorLight: '#ff8544',
      colorDark: '#d04800',
      tagline: 'Explore Optimum Internet Options',
    },
  ],
  
  navigation: [
    { name: 'Home', href: '/' },
    { name: 'Compare', href: '/compare' },
    { name: 'Deals', href: '/deals' },
    { name: 'TV', href: '/tv' },
    { name: 'Bundles', href: '/bundles' },
    { name: 'Why Us', href: '/why-us' },
    { name: 'FAQ', href: '/faq' },
    { name: 'Contact', href: '/contact' },
  ],
  
  footerLinks: {
    company: [
      { name: 'About', href: '/about' },
      { name: 'Why Us', href: '/why-us' },
      { name: 'Contact', href: '/contact' },
    ],
    resources: [
      { name: 'Compare Plans', href: '/compare' },
      { name: 'Current Deals', href: '/deals' },
      { name: 'TV Packages', href: '/tv' },
      { name: 'Bundles', href: '/bundles' },
      { name: 'FAQ', href: '/faq' },
    ],
    providers: [
      { name: 'Verizon', href: '/providers/verizon' },
      { name: 'Spectrum', href: '/providers/spectrum' },
      { name: 'AT&T', href: '/providers/att' },
      { name: 'Optimum', href: '/providers/optimum' },
    ],
    legal: [
      { name: 'Privacy Policy', href: '/privacy-policy' },
      { name: 'Terms & Conditions', href: '/terms-and-conditions' },
      { name: 'Disclosures', href: '/disclosures' },
      { name: 'Accessibility', href: '/accessibility' },
      { name: 'Sitemap', href: '/sitemap' },
    ],
  },
  
  samplePlans: [
    {
      id: 1,
      provider: 'Verizon',
      providerSlug: 'verizon',
      name: 'Fios 300',
      speed: 300,
      price: 49.99,
      priceNote: 'starting price',
      type: 'internet',
      features: ['300 Mbps download', 'No data caps', 'Router included'],
      contract: 'No annual contract may be available',
      promo: true,
    },
    {
      id: 2,
      provider: 'Verizon',
      providerSlug: 'verizon',
      name: 'Fios Gigabit',
      speed: 940,
      price: 89.99,
      priceNote: 'starting price',
      type: 'internet',
      features: ['Up to 940 Mbps', 'No data caps', 'WiFi router included'],
      contract: 'No annual contract may be available',
      promo: true,
    },
    {
      id: 3,
      provider: 'Spectrum',
      providerSlug: 'spectrum',
      name: 'Internet',
      speed: 300,
      price: 49.99,
      priceNote: 'starting price',
      type: 'internet',
      features: ['300 Mbps download', 'No data caps', 'Free modem'],
      contract: 'No contracts',
      promo: false,
    },
    {
      id: 4,
      provider: 'Spectrum',
      providerSlug: 'spectrum',
      name: 'Internet Ultra',
      speed: 500,
      price: 69.99,
      priceNote: 'starting price',
      type: 'internet',
      features: ['500 Mbps download', 'No data caps', 'Free modem'],
      contract: 'No contracts',
      promo: true,
    },
    {
      id: 5,
      provider: 'AT&T',
      providerSlug: 'att',
      name: 'Fiber 300',
      speed: 300,
      price: 55.00,
      priceNote: 'per month with AutoPay',
      type: 'internet',
      features: ['300 Mbps speeds', 'Unlimited data', 'Equipment included'],
      contract: 'No annual contract may be available',
      promo: true,
    },
    {
      id: 6,
      provider: 'AT&T',
      providerSlug: 'att',
      name: 'Fiber 1 Gig',
      speed: 1000,
      price: 80.00,
      priceNote: 'per month with AutoPay',
      type: 'internet',
      features: ['1 Gig speeds', 'Unlimited data', 'WiFi gateway included'],
      contract: 'No annual contract may be available',
      promo: true,
    },
    {
      id: 7,
      provider: 'Optimum',
      providerSlug: 'optimum',
      name: 'Optimum 300',
      speed: 300,
      price: 40.00,
      priceNote: 'for 12 months',
      type: 'internet',
      features: ['300 Mbps download', 'No data caps', 'Free installation may apply'],
      contract: 'Contract terms may apply',
      promo: true,
    },
    {
      id: 8,
      provider: 'Optimum',
      providerSlug: 'optimum',
      name: 'Optimum 1 Gig',
      speed: 940,
      price: 60.00,
      priceNote: 'for 12 months',
      type: 'internet',
      features: ['Up to 940 Mbps', 'No data caps', 'Smart WiFi included'],
      contract: 'Contract terms may apply',
      promo: true,
    },
  ],
  
  bundlePlans: [
    {
      id: 'b1',
      provider: 'Verizon',
      providerSlug: 'verizon',
      name: 'Fios Internet + TV',
      internetSpeed: 300,
      tvChannels: '125+',
      price: 99.99,
      priceNote: 'starting price',
      features: ['300 Mbps internet', '125+ channels', 'DVR service'],
    },
    {
      id: 'b2',
      provider: 'Spectrum',
      providerSlug: 'spectrum',
      name: 'Internet + TV Select',
      internetSpeed: 300,
      tvChannels: '150+',
      price: 109.99,
      priceNote: 'starting price',
      features: ['300 Mbps internet', '150+ channels', 'Free HD'],
    },
    {
      id: 'b3',
      provider: 'AT&T',
      providerSlug: 'att',
      name: 'Internet + DIRECTV',
      internetSpeed: 300,
      tvChannels: '160+',
      price: 104.99,
      priceNote: 'per month',
      features: ['300 Mbps fiber', '160+ channels', 'Regional sports'],
    },
    {
      id: 'b4',
      provider: 'Optimum',
      providerSlug: 'optimum',
      name: 'Internet + TV Basic',
      internetSpeed: 300,
      tvChannels: '220+',
      price: 85.00,
      priceNote: 'for 12 months',
      features: ['300 Mbps internet', '220+ channels', 'Local channels'],
    },
  ],
};

export type Provider = typeof siteConfig.providers[number];
export type Plan = typeof siteConfig.samplePlans[number];
export type BundlePlan = typeof siteConfig.bundlePlans[number];
